---
baseurl: "https://blog.zenithar.org/"
title: "Zenithar'z Blog"
summerization: "html_firstparagraph"
permalinks:
  post: /post/:year/:month/:day/:slug
  project: /project/:year/:month/:day/:slug
indexes:
  tag: "tags"
  topic: "topics"
...
