baseurl = "https://blog.zenithar.org"

languageCode = "fr-fr"
title = "Zenithar'z Blog"
summerization = "html_firstparagraph"

[permalinks]
  post = "/post/:year/:month/:day/:slug"
  project = "/project/:year/:month/:day/:slug"

[indexes]
  tag = "tags"
  topic = "topics"

[params]
  # Warning Keys are case sensitives
  Subtitle = "Il existe moins bien mais c'est plus cher !"
  Description = "Dévéloppeur, bloggeur enthousiaste, curieux de toutes nouvelles technologies liées à la sécurité, l'architecture, et le web."

  # Google analytics
  ga = "UA-8114245-4"

  # Social accounts
  twitter = "zenithar"
  github = "zenithar"
  facebook = "zenithar"
  linkedin = "zenithar"
  disqus = "zenithar"
  gplus = "thibault.normand"

[author]
  Name = "Thibault NORMAND"
  Image = "//www.gravatar.com/avatar/1a2807faf3cca1667ff6f04bf5886eff.png"
  Bio = "Dévéloppeur, bloggeur enthousiaste, curieux de toutes nouvelles technologies liées à la sécurité, l'architecture, et le web."
  Website = "http://zenithar.org"